development:
  adapter: async

test:
  adapter: async

# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: helping-hand-backend_production

production:
  adapter: redis
  url: redis://redistogo:912c6746319f1095bc37b34ec5cd7b61@porgy.redistogo.com:10262/
#   channel_prefix: helping-hand-backend_production

# production:
#   adapter: redis
#   url: redis://helpping-hand.herokuapp.com:6379/1
  # channel_prefix: helping-hand-backend_production

  # redis://localhost:6379